### ISSUE TITLE
Show results only

### ISSUE THREAD

**Issue by ondics** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#14]
The validator is a single page application.

To better embed the validator inside an application it would be helpful to only show the results and to hide the form fields.

This could be implemented e.g. by a (hidden) form parameter `hide_form`.

Can we expect this on the roadmap?

**Comment by init-dcat-ap-de** [comment]
We activated the minimal user interface. For this, use https://www.itb.ec.europa.eu/shacl/dcat-ap.de/uploadm
It removes all form fields from the results page:
![grafik](https://user-images.githubusercontent.com/14979304/166650830-4cdfab0b-125d-4d3a-92e2-75d2edf54467.png)

If there are errors, the details have to be checked within the filebased reports. It this what you are looking for?

**Comment by ondics** [comment]
Looks good. But where are the results in text-form? The user has to download them to check the details of the verification.

We'd prefer a solution where the results are shown (as in the full validator), so that there are no external tools required to improve the submitted data incrementally.

**Comment by costas80** [comment]
The minimal UI variant of the validator has been extended to allow you to toggle between the current summary view and the report's details. This allows you now to view the reported findings without needing to download the validation report.

To toggle to the detailed display click the "View details" button on the result screen:

![image](https://user-images.githubusercontent.com/8297297/167606703-92898d0d-1ea6-458b-b462-9a49c24634c7.png)

Which will display the details and their relevant controls:

![image](https://user-images.githubusercontent.com/8297297/167606913-3960e5e7-25f2-4fac-a56d-d1b727278a07.png)

You can switch back to the summary display by clicking the "View summary" button.
