### ISSUE TITLE
Error: "Die RDF-Sprache konnte nicht für den bereitgestellten Inhalt bestimmt werden."

### ISSUE THREAD

**Issue by ondics** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#16]
The validator guesses the filetype using the file extension. This works when submitting URLs like

    https://opendata-portal/catalog.rdf

But this does not work using urls with parameters:

    https://opendata-portal/catalog.rdf?fq=name:dcat-ap-de-example-dataset

The error message displayed is `Die RDF-Sprache konnte nicht für den bereitgestellten Inhalt bestimmt werden.`

Is this a bug?

**Comment by init-xschule** [comment]
If you don't explicetly state the context syntax, it is guessed by the file extension. Your example does not provide a file extension, therefor the context syntax cannot be guessed.

Please select the context syntax your portal uses to provide the rdf data. (My guess: xml/rdf).

**Comment by init-dcat-ap-de** [comment]
If you don't explicetly state the context syntax, it is guessed by the file extension. Your example does not provide a file extension, therefor the context syntax cannot be guessed.

Please select the context syntax your portal uses to provide the rdf data. (My guess: RDF/XML).

**Comment by ondics** [comment]
The file extension of the URL `https://opendata-portal/catalog.rdf?fq=name:dcat-ap-de-example-dataset` when stripping off the parameters is rdf. It's the last characters after the `.` of the the path. Too complex or unreliable to extract?

**Comment by init-dcat-ap-de** [comment]
You're right, it should be able to extract the file-extension, even though there are parametert.

**Comment by costas80** [comment]
The fix for this is now live. For content loaded via provided URI, any query string extensions are ignored when guessing the resource's content type.
