### ISSUE TITLE
URIs verlinken

### ISSUE THREAD

**Issue by schiersner** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#2]
Es wäre hilfreich, URIs in der Ausgabe zu verlinken.
Beispiel: ` [http://dcat-ap.de/def/dcatde/politicalGeocodingURI] `

**Comment by init-dcat-ap-de** [comment]
Beziehen Sie sich hierbei auf die Fehlermeldungen, die angezeigt werden?
Eine Verlinkung dabei mWn nicht möglich.
