### ISSUE TITLE
Fehlermeldung zu locn:geometry

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#20]
Es gibt eine Fehlermeldung `dct:Location: locn:geometry MUSS ein Literal sein. Es DARF maximal einmal vorhanden sein.` Die scheint mir falsch zu sein. Im [Beispiel des Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#example-beispiel-fur-das-selbe-polygon-aus-geodcat-ap) werden drei Angaben gemacht.

**Comment by init-dcat-ap-de** [comment]
Dieses Beispiel im Konventionenhandbuch soll verschiedene Darstellungen des selben Polygons zeigen. Es handelt sich dabei tatsäch nicht um gültiges DCAT-AP(.de), da DCAT-AP für `locn:geometry` die Kardinalität `0..1` vorgibt.

Das ist natürlich dennoch unglücklich und wir sollten es im Konventionenhandbuch mindestens erwähnen.
