### ISSUE TITLE
Syntax: JSON-LD 

### ISSUE THREAD

**Issue by juligrotebyte** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#22]
Bei Validierung mit Syntax JSON-LD, ist das Validierungsergebnis immer positiv.

**Comment by init-dcat-ap-de** [comment]
Können Sie uns entsprechende Beispieldateien zukommen lassen?

**Comment by juligrotebyte** [comment]
{
  "result": {
    "country": null,
    "keywords": [
      {
        "language": "de",
        "id": "ikgis-cham",
        "label": "IkGIS-Cham"
      },
      {
        "language": "de",
        "id": "open-data",
        "label": "Open Data"
      },
      {
        "language": "de",
        "id": "landkreis-cham",
        "label": "Landkreis Cham"
      },
      {
        "language": "de",
        "id": "bauen-&-wohnen",
        "label": "Bauen & Wohnen"
      }
    ],
    "references": null,
    "catalog": {
      "country": null,
      "creator": null,
      "catalog": null,
      "is_part_of": null,
      "description": {
        "en": "Diese Daten beinhalteten Informationen zum Landkreis Cham und stammen in erster Linie aus der zentralen Datenbank des hiesigen interkommunalen Geoinformationssystems (IkGIS-Cham). Die verfÃ¼gbaren Inhalte entsprechen weitestgehend den intern verwendeten Strukturen."
      },
      "language": [
        {
          "resource": "http://publications.europa.eu/resource/authority/language/DEU",
          "id": "de",
          "label": "German"
        }
      ],
      "availability": null,
      "title": {
        "de": "Landkreis Cham"
      },
      "theme_taxonomy": null,
      "license": null,
      "rights": null,
      "spatial_resource": null,
      "modified": "2023-05-12T10:44:24Z",
      "id": "cham",
      "has_part": null,
      "spatial": null,
      "issued": "2023-05-12T10:44:24Z",
      "homepage": null
    },
    "subject": null,
    "language": null,
    "source": null,
    "type": null,
    "temporal_resolution": null,
    "maintainer": null,
    "relation": null,
    "stat_unit_measure": null,
    "qualified_relation": null,
    "spatial_resource": null,
    "political_geocoding_uri": null,
    "modified": "2023-05-11T11:56:48.214Z",
    "id": "https-www-arcgis-com-home-item-html-id-6956595907d54bba9f747c9aff2ba941-sublayer-70",
    "issued": "2020-07-30T08:47:59Z",
    "spatial": [],
    "temporal": null,
    "is_version_of": null,
    "legal_basis": null,
    "has_version": null,
    "accrual_periodicity": null,
    "geocoding_description": null,
    "access_right": null,
    "political_geocoding_level_uri": null,
    "provenance": null,
    "contributor": null,
    "attribute": null,
    "adms_identifier": null,
    "categories": [],
    "deadline": null,
    "dimension": null,
    "qualified_attribution": null,
    "creator": null,
    "landing_page": [],
    "version_info": null,
    "quality_process_uri": null,
    "sample": null,
    "extended_metadata": null,
    "conforms_to": null,
    "num_series": null,
    "contributor_id": null
  }
}
Es müsste ja ausgegebent werden, dass keine distributions vorhanden sind.

**Comment by init-dcat-ap-de** [comment]
Guten Tag und vielen Dank für dieses Beispiel. 
Hierbei handelt es sich zwar um JSON, aber nicht um JSON-LD, was daran zu erkennen ist, dass keine `"@type"` Eigenschaften verwendet werden. Ein minimales Beipiel eines Datasets, das über keine Distributionen verfügt, könnte wie folgt aussehen;

```JSON
[
    {
        "@id": "_:b0",
        "@type": [
            "http://www.w3.org/2006/vcard/ns#Individual"
        ],
        "http://www.w3.org/2006/vcard/ns#fn": [
            {
                "@value": "Meister, Thomas, Herr"
            }
        ],
        "http://www.w3.org/2006/vcard/ns#hasEmail": [
            {
                "@value": "thomas.meister@example.com"
            }
        ]
    },
    {
        "@id": "https://example.com/dataset/d4ce4e6e-ab89-44cb-bf5c-33a162c234de#dataset",
        "@type": [
            "http://www.w3.org/ns/dcat#Dataset"
        ],
        "http://purl.org/dc/terms/title": [
            {
                "@value": "Badegewässer (Daten) Hamburg"
            }
        ],
        "http://purl.org/dc/terms/description": [
            {
                "@value": "Darstellung der Badegewässer und ihrer Überwachungsmessstellen im Internet."
            }
        ],
        "http://www.w3.org/ns/dcat#contactPoint": [
            {
                "@id": "_:b0"
            }
        ],
        "http://dcat-ap.de/def/dcatde/contributorID": [
            {
                "@id": "http://dcat-ap.de/def/contributors/transparenzportalHamburg"
            }
        ]
    }
]
```

Diese Datei führt zu den erwarteten Fehlern.

Wenn Sie die Datei aus einem System exportieren, versuchen Sie als Export Turtle (.ttl) oder RDF/XML zu erzeugen und wandeln Sie es dann z.B. mit https://www.easyrdf.org/converter in JSON-LD um.

**Comment by juligrotebyte** [comment]
Alles klar, vielen Dank!
