### ISSUE TITLE
Inline validation Fehler

### ISSUE THREAD

**Issue by ondics** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#24]
Die Ausführung von https://www.itb.ec.europa.eu/shacl/dcat-ap.de/uploadm
als POST request bringt den Fehler:

    Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

Der HTML-Code dazu ist:

    <form method="POST" enctype="multipart/form-data" 
            action="https://www.itb.ec.europa.eu/shacl/dcat-ap.de/uploadm" 
            target="output">
        <input style="display:none" type="text" name="uri" value="url-to-ckan-dataset">
        <input type="hidden" name="validationType" value="v20_de_spec_implr">
        <button type="submit">Prüfung starten ...</button>
    </form>
    <iframe name="output" style="width:100%; height:400px;" src='about:blank'></iframe>

Die Lösung dafür wäre, entsprechende Header-Informationen in das Ergebnis einzubauen, z.B.:

    <meta http-equiv="Content-Security-Policy" content="...">

**Comment by init-dcat-ap-de** [comment]
@ondics, ich kann den Fehler nicht reproduzieren. 
Wurde er evtl. bereits behoben?

**Comment by ondics** [comment]
Wenn man den HTML-Code (siehe oben) bei https://codepen.io/pen/ eingibt und `url-to-ckan-dataset` mit einer Url zu einem CKAN-Datensatz ersetzt (z.B. `https://offenedaten.frankfurt.de/catalog.rdf?fq=name%3Ahauskoordinaten-franfurt`), dann:
* wird als Ergebnis nur das Anfrageformular angezeigt (anstelle des Ergebnisses) und
* in der Console kommt der Fehler: `Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src").`

Fehler ist leider noch nicht behoben. Was läuft hier falsch?

**Comment by init-dcat-ap-de** [comment]
@ondics Bitte versuchen Sie es erneut. Das Problem sollte jetzt behoben sein.

**Comment by ondics** [comment]
Ok, funktioniert. Perfekt! Danke.
