### ISSUE TITLE
spdx:algorithm - Meldung "Does not have value spdx:checksumAlgorithm_sha1"

### ISSUE THREAD

**Issue by stefan-korn** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#4]
Der Validator mit Profil "DCAT-AP.de 1.1 Spezifikation & DCAT-AP 2.1 Mandatory & Recommended" gibt folgende Fehlermeldung:

> "Does not have value spdx:checksumAlgorithm_sha1"

Als Wert für spdx:algorithm ist "https://www.dcat-ap.de/def/hashAlgorithms/md/5" laut DCAT-AP.de- Spezifikation gesetzt.

Das passiert sogar mit den Beispieldateien von [https://www.dcat-ap.de/def/dcatde/1.1/examples.zip](https://www.dcat-ap.de/def/dcatde/1.1/examples.zip)

Ist das ein Fehler im Validator oder muss der Wert anders gesetzt werden?

**Comment by init-dcat-ap-de** [comment]
Dabei handelt es sich um einen Fehler in den SHACL-Shapes der SEMIC. 

1. ist das eine Prüfung, die der SPDX-Ontologie überlassen bleiben sollte (diese verfügt inzwischen über weitere mögliche Algorithmen, wobei es da mMn auch noch Probleme in der RDF-Version der Ontologie gibt).

2. ist die Regel der SEMIC unvollständig.

Wie wir mittelfristig damit umgehen, muss noch abschließend geklärt werden. Am einfachsten wäre es wahrscheinlich, wenn die SEMIC-Regel wegfällt und wir unsere eigene Regel mit unserer eigenen Codeliste verfassen.

Getestet wird außerdem ein Workaround via rdfs:sameAs.

In allen Fällen sollte es auf unserer Seite behoben werden, ohne dass die Angaben der Datenbereitsteller geändert werden müssen.

**Comment by init-dcat-ap-de** [comment]
Dieses Problem wurde behoben, da die fehlerhafte SEMIC-Regel nicht mehr eingebunden wird.
