### ISSUE TITLE
json-ld validation: An error occurred during the validation [Error writing RDF model]

### ISSUE THREAD

**Issue by markaspot** [GovDataOfficial/DCAT-AP.de-SHACL-Validation#8]
Bei der Validierung eines der Kölner Datensätze tritt der beschriebene Fehler auf. Könnten Sie prüfen, ob es an der hochgeladenen Datei oder dem Validator liegt, und den Validator ggf. fixen? siehe json unten) cc: @egovcologne

<img width="688" alt="Screenshot 2021-01-25 at 11 52 50" src="https://user-images.githubusercontent.com/212898/105696952-36dea180-5f04-11eb-9eb6-0be3fdb0ddf9.png">

<img width="1173" alt="Screenshot 2021-01-25 at 11 52 59" src="https://user-images.githubusercontent.com/212898/105696939-33e3b100-5f04-11eb-9006-7ea6532b1eef.png">

[vornamen.json.txt](https://github.com/GovDataOfficial/DCAT-AP.de-SHACL-Validation/files/5866063/vornamen.json.txt)

**Comment by GKStGovData** [comment]
@markaspot danke für den Beitrag. Könnten Sie einen Link zu der Datei bereitstellen?

**Comment by markaspot** [comment]
hängt unter dem Screenshot ;)

**Comment by GKStGovData** [comment]
@markaspot Danke! Die angehängte Version habe ich als .json abgespeichert und konnte Sie dann validieren. Allerdings kam es bei wiederholten Versuchen sporadisch zu dem oben aufgezeigten Fehler, ist also vermutlich kein Fehler an der Datei sondern am Validator. Wir geben das auch mal an die Verantwortlichen bei ITB weiter.   
![VornamenSuccess](https://user-images.githubusercontent.com/40267626/105706622-0e5da400-5f12-11eb-8ce7-7c81a1bf5d02.PNG)

**Comment by markaspot** [comment]
Vielen Dank für die schnelle Reaktion.

**Comment by init-dcat-ap-de** [comment]
@markaspot ich konnte den Fehler nicht mit der angehängten Datei reproduzieren. 
Der Validator wurde in letzter Zeit weiterentwickelt. Ich schließe das Issue in der Annahme, dass der Fehler behoben wurde.
